### ISSUE TITLE
TODO bis zur ALPHA

### ISSUE THREAD

**Issue by Dragonflysots** [SBird1337/source_of_the_sovereign#93]
- [x] Maps bis zur Alpha mappen
- [x] Tilestes bir zur Alpha erstellen und einfügen
- [ ] Tileset Animationen erstellen
- [ ] Türanimationen Erstellen (#90)
- [x] Wilde Pokémon Daten
- [ ] Trainerdaten
- [ ] NPC Texte
- [ ] Musikstücke bis Alpha aufbereiten (fehlende fertigstellen)
- [ ] Fehlende Attacken / Items / Fähigkeiten vorerst nicht einbauen (ausblenden)
- [x] Overworld Sprites aufbereiten
- [ ] ...

PS: Das meiste erscheint viel, ist aber relativ einfach und schnell erledigt. Das aufwendigste und zeitintensivste sind die Maps sowie die Tilesets. Sie machen quasi 70% des Zeitaufwandes aus.

**Comment by ipatix** [comment]
Coole Idee. Hier hat man hoffentlich mal ein bisschen Überblick.

**Comment by SBird1337** [comment]
Wenn man sich irgendwie an Conventions halten möchte, könnte man die einzelnen Punkte zu Issues machen und dann einen Alpha Milestone erstellen, ansonsten nette Übersicht^^
